name: Build assets for release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - name: Set version in env
      run: echo "CLI_VERSION=$(git tag | tail -1)" >> $GITHUB_ENV
    - uses: wangyoucao577/go-release-action@v1.41
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.19"
        project_path: "./cmd"
        binary_name: "create-grammy"
        sha256sum: "TRUE"
        overwrite: "TRUE"
        compress_assets: "FALSE"
        asset_name: create-grammy-${{ matrix.goos }}_${{ matrix.goarch }}
        executable_compression: "upx -9 -k"
        ldflags: "-s -w -X github.com/grammyjs/create-grammy/internal/utils.Version=${{ env.CLI_VERSION }}"